[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "alf"
version = "0.2.0"
description = "Peter's local computing companion"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4",
    "rich",
    "sympy",
    "trafilatura>=2.2.0",
]


[project.scripts]
alf = "alf.main:main"

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
]
